services:
  - type: web
    name: smartshield-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000
    healthCheckPath: /packets

